language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
env:
  - SUITE=core
#  - SUITE=libraries
#  - SUITE=database/mysql
#  - SUITE=database/mysqli
#  - SUITE=database/pgsql
#  - SUITE=database/sqlite
#  - SUITE=database/pdo/mysql
#  - SUITE=database/pdo/pgsql
#  - SUITE=database/pdo/sqlite

before_script:
  - composer install --dev --no-progress
#  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ci_test;' -U postgres; fi"
#  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'create database ci_test;' -U postgres; fi"
#  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"

script: phpunit --coverage-text --configuration tests/travis/$SUITE.phpunit.xml
#script: phpunit --coverage-text --configuration tests/phpunit.xml

branches:
  only:
    - master
    - /^feature\/.+$/
